#!/bin/sh
set -e

echo "Downloading $pkg..."
wget https://github.com/fastfetch-cli/fastfetch/archive/refs/tags/2.56.0.tar.gz -o fastfetch.tar.gz

echo "Extracting FastFetch..."
tar -xf "fastfetch.tar.gz"
cd fastfetch
