#!/bin/sh
set -e

echo "Extracting FastFetch..."
tar -xf "2.56.0.tar.gz"
cd "2.56.0" || exit 1

echo "Changing Dir to build..."
mkdir -p build
cd build

echo "Cmake..."
cmake .. -DCMAKE_BUILD_TYPE=Release
cmake --build .
